/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tutorial;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AnswerStruct implements org.apache.thrift.TBase<AnswerStruct, AnswerStruct._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AnswerStruct");

  private static final org.apache.thrift.protocol.TField ANSWER_OBJECT_FIELD_DESC = new org.apache.thrift.protocol.TField("answerObject", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AnswerStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AnswerStructTupleSchemeFactory());
  }

  public String answerObject; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ANSWER_OBJECT((short)1, "answerObject");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ANSWER_OBJECT
          return ANSWER_OBJECT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ANSWER_OBJECT, new org.apache.thrift.meta_data.FieldMetaData("answerObject", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AnswerStruct.class, metaDataMap);
  }

  public AnswerStruct() {
  }

  public AnswerStruct(
    String answerObject)
  {
    this();
    this.answerObject = answerObject;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AnswerStruct(AnswerStruct other) {
    if (other.isSetAnswerObject()) {
      this.answerObject = other.answerObject;
    }
  }

  public AnswerStruct deepCopy() {
    return new AnswerStruct(this);
  }

  @Override
  public void clear() {
    this.answerObject = null;
  }

  public String getAnswerObject() {
    return this.answerObject;
  }

  public AnswerStruct setAnswerObject(String answerObject) {
    this.answerObject = answerObject;
    return this;
  }

  public void unsetAnswerObject() {
    this.answerObject = null;
  }

  /** Returns true if field answerObject is set (has been assigned a value) and false otherwise */
  public boolean isSetAnswerObject() {
    return this.answerObject != null;
  }

  public void setAnswerObjectIsSet(boolean value) {
    if (!value) {
      this.answerObject = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ANSWER_OBJECT:
      if (value == null) {
        unsetAnswerObject();
      } else {
        setAnswerObject((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ANSWER_OBJECT:
      return getAnswerObject();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ANSWER_OBJECT:
      return isSetAnswerObject();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AnswerStruct)
      return this.equals((AnswerStruct)that);
    return false;
  }

  public boolean equals(AnswerStruct that) {
    if (that == null)
      return false;

    boolean this_present_answerObject = true && this.isSetAnswerObject();
    boolean that_present_answerObject = true && that.isSetAnswerObject();
    if (this_present_answerObject || that_present_answerObject) {
      if (!(this_present_answerObject && that_present_answerObject))
        return false;
      if (!this.answerObject.equals(that.answerObject))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(AnswerStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    AnswerStruct typedOther = (AnswerStruct)other;

    lastComparison = Boolean.valueOf(isSetAnswerObject()).compareTo(typedOther.isSetAnswerObject());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnswerObject()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answerObject, typedOther.answerObject);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AnswerStruct(");
    boolean first = true;

    sb.append("answerObject:");
    if (this.answerObject == null) {
      sb.append("null");
    } else {
      sb.append(this.answerObject);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AnswerStructStandardSchemeFactory implements SchemeFactory {
    public AnswerStructStandardScheme getScheme() {
      return new AnswerStructStandardScheme();
    }
  }

  private static class AnswerStructStandardScheme extends StandardScheme<AnswerStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AnswerStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ANSWER_OBJECT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.answerObject = iprot.readString();
              struct.setAnswerObjectIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AnswerStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.answerObject != null) {
        oprot.writeFieldBegin(ANSWER_OBJECT_FIELD_DESC);
        oprot.writeString(struct.answerObject);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AnswerStructTupleSchemeFactory implements SchemeFactory {
    public AnswerStructTupleScheme getScheme() {
      return new AnswerStructTupleScheme();
    }
  }

  private static class AnswerStructTupleScheme extends TupleScheme<AnswerStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AnswerStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAnswerObject()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAnswerObject()) {
        oprot.writeString(struct.answerObject);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AnswerStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.answerObject = iprot.readString();
        struct.setAnswerObjectIsSet(true);
      }
    }
  }

}

